# eureka客户端生产环境配置
eureka: 
    client:
        region: default
# 客户端拉取服务注册信息间隔时间,默认30。配置此值是为了了解其作用
        registryFetchIntervalSeconds: 30
# 服务发现服务默认URL
        serviceUrl: 
            defaultZone: 
                http://localhost:8761/eureka/
# 日志级别生产环境配置
logging: 
    level: 
        com.netflix.discovery: 
            OFF
        org.springframework.cloud: 
            DEBUG