# eureka开发环境配置
spring:
  profiles: 
    active: dev
eureka: 
  instance: 
    hostname: 
      localhost
  client: 
    serviceUrl: 
      defaultZone: 
        http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka:  
      false
    fetch-registry: 
      false